import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowUpRight, Check, Crown, Flame, Grip, Menu, MousePointer2, Search, Shield, Sparkles, X, ZoomIn, ZoomOut, RotateCcw } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const RAW = [
['ai','AI','Technology',25],['software','Software','Technology',10],['programming','Programming','Technology',10],['javascript','JavaScript','Technology',10],['python','Python','Technology',10],['web-development','Web Development','Technology',10],['cybersecurity','Cybersecurity','Technology',10],['robotics','Robotics','Technology',25],['3d-printing','3D Printing','Technology',10],['hardware','Hardware','Technology',10],['cloud','Cloud','Technology',10],['open-source','Open Source','Technology',10],['apps','Apps','Technology',10],['startups','Startups','Technology',25],['saas','SaaS','Technology',25],['data','Data','Technology',10],['ar-vr','AR/VR','Technology',10],['blockchain','Blockchain','Technology',10],['bitcoin','Bitcoin','Technology',25],['tech','Tech','Technology',100],
['marketing','Marketing','Business',10],['advertising','Advertising','Business',10],['ecommerce','E-commerce','Business',10],['finance','Finance','Business',25],['investing','Investing','Business',10],['entrepreneurship','Entrepreneurship','Business',10],['consulting','Consulting','Business',10],['freelancing','Freelancing','Business',5],['real-estate','Real Estate','Business',10],['banking','Banking','Business',25],['venture-capital','Venture Capital','Business',25],['productivity','Productivity','Business',10],['jobs','Jobs','Business',10],['money','Money','Business',25],['business','Business','Business',100],
['space','Space','Science',25],['rockets','Rockets','Science',10],['aerospace','Aerospace','Science',25],['aviation','Aviation','Science',10],['engineering','Engineering','Science',25],['physics','Physics','Science',10],['chemistry','Chemistry','Science',10],['biology','Biology','Science',10],['astronomy','Astronomy','Science',10],['nuclear','Nuclear','Science',10],['energy','Energy','Science',10],['climate','Climate','Science',10],['science','Science','Science',25],['mars','Mars','Science',25],['earth','Earth','Science',100],
['gaming','Gaming','Culture',25],['music','Music','Culture',25],['movies','Movies','Culture',10],['anime','Anime','Culture',10],['memes','Memes','Culture',25],['youtube','YouTube','Culture',25],['streaming','Streaming','Culture',10],['tiktok','TikTok','Culture',25],['football','Football','Culture',25],['sports','Sports','Culture',25],['photography','Photography','Culture',10],['art','Art','Culture',10],['fashion','Fashion','Culture',10],['travel','Travel','Culture',10],['culture','Culture','Culture',25],
['ireland','Ireland','Places',25],['dublin','Dublin','Places',25],['belfast','Belfast','Places',10],['uk','UK','Places',50],['london','London','Places',50],['europe','Europe','Places',50],['usa','USA','Places',50],['new-york','New York','Places',25],['california','California','Places',25],['canada','Canada','Places',25],['australia','Australia','Places',25],['japan','Japan','Places',25],['south-korea','South Korea','Places',10],['china','China','Places',25],['india','India','Places',25],['singapore','Singapore','Places',10],['germany','Germany','Places',25],['france','France','Places',25],['italy','Italy','Places',10],['world','World','Places',100],
['cars','Cars','Wildcard',10],['coffee','Coffee','Wildcard',5],['food','Food','Wildcard',10],['fitness','Fitness','Wildcard',10],['education','Education','Wildcard',10],['university','University','Wildcard',10],['work','Work','Wildcard',5],['internet','Internet','Wildcard',100],['future','Future','Wildcard',25],['freedom','Freedom','Wildcard',10],['luxury','Luxury','Wildcard',10],['everything','Everything','Wildcard',100],['nothing','Nothing','Wildcard',10],['electric-cars','Electric Cars','Wildcard',10],['design','Design','Wildcard',10]
];
const seededOwners={ai:{owner:'@northstar',stake:32},space:{owner:'@orbital',stake:47},ireland:{owner:'@foundry',stake:27},gaming:{owner:'@pixelworks',stake:41},photography:{owner:'@luma',stake:12}};
const territories=RAW.map(([id,name,category,price])=>({id,name,category,price,owner:seededOwners[id]?.owner??null,stake:seededOwners[id]?.stake??price}));
const cats=['Technology','Business','Science','Culture','Places','Wildcard'];
const centers={Technology:[360,285],Business:[840,275],Science:[355,770],Culture:[855,770],Places:[1395,285],Wildcard:[1395,770]};
const tones={Technology:'mint',Business:'violet',Science:'cyan',Culture:'peach',Places:'gold',Wildcard:'rose'};
const links=[['ai','data'],['ai','python'],['ai','robotics'],['ai','saas'],['software','programming'],['programming','javascript'],['cybersecurity','blockchain'],['startups','saas'],['startups','venture-capital'],['space','rockets'],['space','aerospace'],['space','astronomy'],['rockets','engineering'],['aerospace','aviation'],['engineering','physics'],['mars','astronomy'],['earth','climate'],['energy','engineering'],['gaming','youtube'],['gaming','streaming'],['music','movies'],['music','tiktok'],['football','sports'],['photography','art'],['fashion','design'],['travel','culture'],['ireland','dublin'],['ireland','belfast'],['uk','london'],['usa','new-york'],['usa','california'],['japan','south-korea'],['europe','france'],['europe','germany'],['europe','italy'],['internet','ai'],['internet','software'],['internet','gaming'],['future','space'],['future','ai'],['education','university'],['cars','electric-cars'],['business','money'],['finance','investing']];
function layout(items){const out={};for(const cat of cats){const list=items.filter(t=>t.category===cat),[cx,cy]=centers[cat],cols=(cat==='Technology'||cat==='Places')?5:4,gapX=140,gapY=128,rows=Math.ceil(list.length/cols),sx=cx-(cols-1)*gapX/2,sy=cy-(rows-1)*gapY/2;list.forEach((t,i)=>{const col=i%cols,row=Math.floor(i/cols);out[t.id]={x:sx+col*gapX+(row%2?28:0),y:sy+row*gapY};});}return out;}
const POS=layout(territories);
function priceFor(t){return t.owner?Math.max(t.stake+2,Math.ceil(t.stake*1.1)):t.price;}
function App(){
 const [items,setItems]=useState(territories),[active,setActive]=useState(null),[hovered,setHovered]=useState(null),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[zoom,setZoom]=useState(.86),[pan,setPan]=useState({x:0,y:0}),[dragging,setDragging]=useState(false);const drag=useRef(null),mapRef=useRef(null);
 const filtered=useMemo(()=>items.filter(t=>(category==='All'||t.category===category)&&t.name.toLowerCase().includes(query.toLowerCase())),[items,category,query]);
 const visible=new Set(filtered.map(t=>t.id));
 const related=useMemo(()=>{if(!hovered)return new Set();const s=new Set([hovered]);links.forEach(([a,b])=>{if(a===hovered)s.add(b);if(b===hovered)s.add(a)});return s},[hovered]);
 const current=active?items.find(t=>t.id===active):null,value=items.reduce((s,t)=>s+(t.owner?t.stake:0),0),owned=items.filter(t=>t.owner).length;
 useEffect(()=>{const el=mapRef.current;if(!el)return;const wheel=e=>{e.preventDefault();setZoom(z=>Math.max(.62,Math.min(1.35,+(z*(e.deltaY>0?.94:1.065)).toFixed(3))))};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel)},[]);
 const down=e=>{if(e.button!==0)return;drag.current={x:e.clientX-pan.x,y:e.clientY-pan.y};setDragging(true);e.currentTarget.setPointerCapture?.(e.pointerId)};const move=e=>{if(!drag.current)return;setPan({x:e.clientX-drag.current.x,y:e.clientY-drag.current.y})};const up=()=>{drag.current=null;setDragging(false)};const claim=t=>{const p=priceFor(t);setItems(prev=>prev.map(x=>x.id===t.id?{...x,owner:'@you',stake:p}:x));setActive(null)};
 return <div className="app-shell"><header className="topbar"><a className="brand" href="#top">EMPIRE<span>.LOL</span></a><nav className="nav"><a href="#map">Map</a><a href="#leaderboard">Leaderboard</a><a href="#activity">Activity</a><a href="#how">How it works</a></nav><button className="ghost-btn desktop-only">Build your empire <ArrowUpRight size={15}/></button><button className="mobile-menu"><Menu size={19}/></button></header>
 <main id="top"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> THE INTERNET IS FOR SALE</div><h1>OWN THE<br/><em>INTERNET.</em></h1><p>Claim territory. Defend it. Conquer everything.</p><div className="hero-actions"><a className="primary-btn" href="#map">Explore the map <ArrowUpRight size={17}/></a><a className="text-link" href="#how">How it works <ArrowUpRight size={15}/></a></div></div><div className="hero-stat-card"><div className="stat-card-label">LIVE EMPIRE VALUE</div><div className="big-number">£{value.toLocaleString()}</div><div className="mini-grid"><span><b>{owned}</b> territories owned</span><span><b>100</b> total territories</span></div><div className="pulse-line"><span>●</span> Live map activity</div></div></section>
 <section id="map" className="map-section"><div className="section-head map-head"><div><span className="kicker">01 / THE MAP</span><h2>Explore the internet.</h2><p className="map-subtitle">Niches pull together. Follow the strings. Discover what connects.</p></div><div className="map-tools"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a territory"/></div><div className="zoom-readout">{Math.round(zoom*100)}%</div></div></div><div className="category-row">{['All',...cats].map(c=><button key={c} className={category===c?'chip active':'chip'} onClick={()=>setCategory(c)}>{c}</button>)}</div>
 <div ref={mapRef} className={`map-shell ${dragging?'is-dragging':''}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><div className="map-noise"/><div className="map-grid-lines"/><div className="map-world" style={{transform:`translate3d(${pan.x}px,${pan.y}px,0) scale(${zoom})`}}>
 <svg className="map-links" viewBox="0 0 1380 930" preserveAspectRatio="none"><defs><linearGradient id="threadGradient" x1="0" x2="1"><stop offset="0" stopColor="#93ff48"/><stop offset=".5" stopColor="#cbd2d9"/><stop offset="1" stopColor="#ffbd91"/></linearGradient></defs>{links.map(([a,b],i)=>{const pa=POS[a],pb=POS[b];if(!pa||!pb||!visible.has(a)||!visible.has(b))return null;const hot=hovered&&(related.has(a)||related.has(b)),mx=(pa.x+pb.x)/2,my=(pa.y+pb.y)/2-(Math.abs(pb.x-pa.x)<240?28:50);return <path key={i} d={`M${pa.x} ${pa.y} C${mx} ${my} ${mx} ${my} ${pb.x} ${pb.y}`} className={hot?'thread hot':'thread'}/>})}{cats.slice(0,-1).map((c,i)=>{const a=centers[c],b=centers[cats[i+1]];return <path key={c} d={`M${a[0]} ${a[1]} C${(a[0]+b[0])/2} ${a[1]-90} ${(a[0]+b[0])/2} ${b[1]+90} ${b[0]} ${b[1]}`} className="bridge-thread"/>})}</svg>
 {cats.map(cat=>{const [x,y]=centers[cat];return <div key={cat} className="cluster-label" style={{left:x,top:y-150}}><span>{cat}</span><small>{filtered.filter(t=>t.category===cat).length} territories</small></div>})}
 {filtered.map(t=>{const p=POS[t.id],size=t.price>=100?102:t.price>=50?92:t.price>=25?82:66,isHot=hovered===t.id,dim=hovered&&!related.has(t.id),connected=hovered&&related.has(t.id);return <button key={t.id} className={`bubble ${tones[t.category]} ${t.owner?'owned':''} ${isHot?'hovered':''} ${dim?'dim':''} ${connected?'connected':''}`} style={{left:p.x,top:p.y,width:size,height:size,zIndex:isHot?30:10}} onMouseEnter={()=>setHovered(t.id)} onMouseLeave={()=>setHovered(null)} onClick={e=>{e.stopPropagation();setActive(t.id)}}><span className="bubble-shine"/><span className="bubble-content"><b>{t.name}</b><small>{t.owner||`£${t.price}`}</small>{t.owner&&<i>£{t.stake}</i>}</span>{t.owner&&<span className="owner-mark"><Check size={9}/></span>}</button>})}</div><div className="map-overlay top-left"><b>THE INTERNET / V1</b><span>100 curated territories</span></div><div className="map-overlay legend"><i className="legend-dot open"/> OPEN <i className="legend-dot owned"/> OWNED</div><div className="map-overlay bottom-left"><Grip size={13}/> Drag to explore <b/> Scroll to zoom</div><div className="map-controls"><button onClick={()=>setZoom(z=>Math.min(1.35,+(z*1.14).toFixed(3)))}><ZoomIn size={16}/></button><button onClick={()=>setZoom(z=>Math.max(.62,+(z*.87).toFixed(3)))}><ZoomOut size={16}/></button><button onClick={()=>{setPan({x:0,y:0});setZoom(.86)}}><RotateCcw size={16}/></button></div></div></section>
 <section className="split-section"><div className="panel" id="activity"><div className="panel-head"><div><span className="kicker">02 / ACTIVITY</span><h3>Live on the map.</h3></div><span className="live-badge">● LIVE</span></div>{[['@northstar','conquered','AI',32,'2m'],['@orbital','defended','SPACE',47,'7m'],['@foundry','conquered','IRELAND',27,'13m'],['@pixelworks','conquered','GAMING',41,'21m']].map((r,i)=><div className="activity-row" key={i}><div className="activity-icon">{r[1]==='defended'?<Shield size={14}/>:<Flame size={14}/>}</div><div><b>{r[0]}</b> {r[1]} <strong>{r[2]}</strong><span>{r[4]} ago</span></div><em>£{r[3]}</em></div>)}</div><div className="panel" id="leaderboard"><div className="panel-head"><div><span className="kicker">03 / RANKINGS</span><h3>Top empires.</h3></div><Crown size={18}/></div>{[['@orbital','£482'],['@northstar','£321'],['@pixelworks','£241'],['@foundry','£187'],['@luma','£96']].map(([u,v],i)=><div className="rank-row" key={u}><span>0{i+1}</span><b>{u}</b><strong>{v}</strong></div>)}</div></section>
 <section id="how" className="how-section"><span className="kicker">04 / THE RULES</span><h2>A simple game.<br/><span>One brutal rule.</span></h2><div className="how-grid"><div><span>01</span><h4>Claim</h4><p>Pick an open territory and become its first owner.</p></div><div><span>02</span><h4>Conquer</h4><p>Anyone can take it by beating the current stake.</p></div><div><span>03</span><h4>Defend</h4><p>Lose your territory? Pay the next stake and take it back.</p></div><div><span>04</span><h4>Share</h4><p>Every takeover becomes a public moment worth sharing.</p></div></div></section></main>
 <footer><div className="brand footer-brand">EMPIRE<span>.LOL</span></div><div className="footer-copy">Own the internet. One territory at a time.</div><div className="footer-links"><a href="#map">Map</a><a href="#leaderboard">Rankings</a><a href="#how">Rules</a></div></footer>
 {current&&<div className="modal-backdrop" onClick={()=>setActive(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close-btn" onClick={()=>setActive(null)}><X size={18}/></button><div className={`modal-icon ${tones[current.category]}`}/><span className="kicker">{current.category} / TERRITORY</span><h3>{current.name}</h3><div className="modal-owner"><span>Current owner</span><strong>{current.owner||'Unclaimed'}</strong></div><div className="modal-price"><span>{current.owner?'Next stake':'Starting price'}</span><b>£{priceFor(current)}</b></div><button className="primary-btn wide" onClick={()=>claim(current)}>{current.owner?'Conquer territory':'Claim territory'} <ArrowUpRight size={16}/></button><p className="demo-note"><Sparkles size={13}/> Prototype checkout is mocked.</p></div></div>}
 </div>}
createRoot(document.getElementById('root')).render(<App/>);
