import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, ArrowUpRight, ChevronLeft, ChevronRight, Crown, Search, Shield, Sparkles, X, ZoomIn, ZoomOut } from 'lucide-react';
import './styles.css';

const WORLDS = [
  { id:'technology', name:'Technology', eyebrow:'THE BUILDERS', tone:'mint', description:'Software, AI, hardware and tools shaping what comes next.', topics:['AI','Software','Programming','Robotics','3D Printing','Hardware','Cloud','Open Source','Apps','Startups','SaaS','Data','AR/VR','Blockchain','Bitcoin','Tech'] },
  { id:'science', name:'Science', eyebrow:'THE FRONTIER', tone:'cyan', description:'Questions, discoveries and machines pushing beyond the known.', topics:['Space','Rockets','Aerospace','Aviation','Engineering','Physics','Chemistry','Biology','Astronomy','Nuclear','Energy','Climate','Science','Mars','Earth'] },
  { id:'business', name:'Business', eyebrow:'THE MARKET', tone:'violet', description:'Capital, companies and the systems that move money.', topics:['Marketing','Advertising','E-commerce','Finance','Investing','Entrepreneurship','Consulting','Freelancing','Real Estate','Banking','Venture Capital','Productivity','Jobs','Money','Business'] },
  { id:'culture', name:'Culture', eyebrow:'THE SIGNAL', tone:'peach', description:'The things people watch, play, listen to and obsess over.', topics:['Gaming','Music','Movies','Anime','Memes','YouTube','Streaming','TikTok','Football','Sports','Photography','Art','Fashion','Travel','Culture'] },
  { id:'places', name:'Places', eyebrow:'THE WORLD', tone:'gold', description:'Countries, cities and places that connect everything else.', topics:['Ireland','Dublin','Belfast','UK','London','Europe','USA','New York','California','Canada','Australia','Japan','South Korea','China','India','Singapore','Germany','France','Italy','World'] },
  { id:'life', name:'Life', eyebrow:'THE REST', tone:'rose', description:'Interests, ideas and the weird edges of the internet.', topics:['Cars','Coffee','Food','Fitness','Education','University','Work','Internet','Future','Freedom','Luxury','Everything','Nothing','Electric Cars','Design'] },
];

const SEEDED = { AI:{owner:'@northstar',stake:32}, Space:{owner:'@orbital',stake:47}, Ireland:{owner:'@foundry',stake:27}, Gaming:{owner:'@pixelworks',stake:41}, Photography:{owner:'@luma',stake:12} };
const BASE_PRICES = { Tech:100, Internet:100, Everything:100, Earth:100, Business:100, World:100, AI:25, Space:25, Gaming:25, Bitcoin:25, Startups:25, Engineering:25 };
const LINKS = { AI:['Data','Python','Robotics','SaaS','Software','Future'], Software:['Programming','Cloud','Apps','AI'], Programming:['JavaScript','Python','Open Source','Software'], Robotics:['3D Printing','Hardware','Engineering'], Startups:['SaaS','Venture Capital','Entrepreneurship','Tech'], Bitcoin:['Blockchain','Finance'], Space:['Rockets','Aerospace','Astronomy','Mars','Future'], Rockets:['Engineering','Space'], Aerospace:['Aviation','Engineering','Space'], Engineering:['Physics','3D Printing','Energy'], Earth:['Climate','Energy'], Astronomy:['Mars'], Finance:['Investing','Banking','Money','Venture Capital'], Marketing:['Advertising','E-commerce'], Business:['Money','Entrepreneurship'], Gaming:['YouTube','Streaming','Memes'], Music:['Movies','TikTok','Culture'], Football:['Sports'], Photography:['Art'], Fashion:['Art'], Travel:['Culture'], Ireland:['Dublin','Belfast'], UK:['London'], Europe:['France','Germany','Italy'], USA:['New York','California'], Japan:['South Korea'], World:['Europe','USA','UK'], Cars:['Electric Cars','Engineering'], Education:['University'], Design:['Art'], Fitness:['Sports'], Food:['Travel'], Internet:['AI','Software','Gaming','YouTube','Marketing'], Future:['AI','Space'] };

function priceFor(topic) { const seeded=SEEDED[topic]; return seeded ? Math.max(seeded.stake+2, Math.ceil(seeded.stake*1.1)) : (BASE_PRICES[topic] ?? 10); }
function initialTopic(name) { const seeded=SEEDED[name]; return { name, owner: seeded?.owner ?? null, stake: seeded?.stake ?? 0, price: priceFor(name) }; }
function nextPrice(topic) { return topic.owner ? Math.max(topic.stake+2, Math.ceil(topic.stake*1.1)) : topic.price; }
function App(){
  const [worldId,setWorldId]=useState(null); const [active,setActive]=useState(null); const [query,setQuery]=useState(''); const [claimed,setClaimed]=useState({}); const [zoom,setZoom]=useState(1);
  const worlds=useMemo(()=>WORLDS.map(w=>({...w,topicData:w.topics.map(t=>claimed[t]||initialTopic(t))})),[claimed]);
  const world=worlds.find(w=>w.id===worldId)||null;
  const all=useMemo(()=>worlds.flatMap(w=>w.topicData.map(t=>({...t,world:w}))),[worlds]);
  const hits=useMemo(()=>{const q=query.trim().toLowerCase();return q?all.filter(t=>t.name.toLowerCase().includes(q)).slice(0,8):[]},[query,all]);
  const activeTopic=active?(world?.topicData.find(t=>t.name===active)||all.find(t=>t.name===active)):null;
  const totalOwned=all.filter(t=>t.owner).length; const totalValue=all.reduce((s,t)=>s+(t.owner?t.stake:0),0);
  const positions=[[24,25],[40,17],[57,25],[74,19],[86,33],[17,47],[31,43],[47,49],[63,43],[79,51],[90,48],[22,72],[37,80],[51,71],[66,80],[82,72],[53,55]];
  const worldPositions=[{x:29,y:31,size:230,r:-4},{x:69,y:31,size:215,r:4},{x:25,y:69,size:225,r:3},{x:75,y:69,size:235,r:-3},{x:50,y:17,size:200,r:2},{x:50,y:85,size:200,r:-2}];
  function openWorld(id){setWorldId(id);setActive(null);setQuery('');setZoom(1)}
  function claim(topic){const n=nextPrice(topic);setClaimed(p=>({...p,[topic.name]:{...topic,owner:'@you',stake:n}}));setActive(null)}
  return <div className="app-shell">
    <header className="topbar"><a href="#top" className="brand">EMPIRE<span>.LOL</span></a><nav><a href="#atlas">Atlas</a><a href="#activity">Activity</a><a href="#rankings">Rankings</a><a href="#how">How it works</a></nav><button className="header-cta">Build your empire <ArrowUpRight size={14}/></button></header>
    <main id="top">
      <section className="hero"><div><div className="eyebrow"><span className="live-dot"/> THE INTERNET IS FOR SALE</div><h1>OWN THE<br/><em>INTERNET.</em></h1><p>Explore the atlas. Find a territory people care about. Claim it, defend it, and put your name on it.</p><div className="hero-actions"><a className="primary-btn" href="#atlas">Explore the atlas <ArrowRight size={16}/></a><a className="secondary-link" href="#how">How it works <ArrowUpRight size={14}/></a></div></div><aside className="stats-card"><span>LIVE EMPIRE VALUE</span><strong>£{totalValue.toLocaleString()}</strong><div><b>{totalOwned}</b> owned <b>100</b> territories <b>6</b> worlds</div><small><i/> Atlas is live</small></aside></section>
      <section id="atlas" className="atlas-section"><div className="atlas-head"><div><span className="kicker">01 / ATLAS</span><div className="title-row">{world&&<button className="back-btn" onClick={()=>{setWorldId(null);setActive(null);setZoom(1)}}><ChevronLeft size={15}/> Internet</button>}<h2>{world?world.name:'Explore the internet.'}</h2></div><p>{world?world.description:'Six worlds. A hundred territories. Start broad, then dive into whatever catches your eye.'}</p></div><div className="search-wrap"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the internet"/>{query&&<button onClick={()=>setQuery('')}><X size={14}/></button>}</div></div>
        {hits.length>0&&<div className="search-panel">{hits.map(x=><button key={x.world.id+x.name} onClick={()=>{openWorld(x.world.id);setActive(x.name)}}><span className={`search-dot ${x.world.tone}`}/><strong>{x.name}</strong><small>{x.world.name}</small><ChevronRight size={14}/></button>)}</div>}
        <div className={`atlas-frame ${world?'in-world':''}`}>
          <div className="frame-glow one"/><div className="frame-glow two"/><div className="frame-grid"/>
          {!world ? <><div className="internet-core"><div className="core-ring"/><strong>THE<br/>INTERNET</strong><small>100 TERRITORIES</small></div>{worlds.map((w,i)=>{const p=worldPositions[i];const owned=w.topicData.filter(t=>t.owner).length;return <button key={w.id} className={`world-orb ${w.tone}`} style={{left:p.x+'%',top:p.y+'%',width:p.size,height:p.size,transform:`translate(-50%,-50%) rotate(${p.r}deg)`}} onClick={()=>openWorld(w.id)}><span className="orb-shine"/><small>{w.eyebrow}</small><strong>{w.name}</strong><em>{owned}/{w.topics.length} owned</em><i>{w.topics[0]}</i><i className="second">{w.topics[Math.min(4,w.topics.length-1)]}</i></button>})}</> : <><div className="world-toolbar"><div><span className={`search-dot ${world.tone}`}/><strong>{world.eyebrow}</strong><small>{world.topicData.filter(t=>t.owner).length}/{world.topicData.length} owned</small></div><div className="zoom"><button onClick={()=>setZoom(z=>Math.min(1.2,+(z+.1).toFixed(2)))}><ZoomIn size={14}/></button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.max(.85,+(z-.1).toFixed(2)))}><ZoomOut size={14}/></button></div></div><div className="topic-field" style={{transform:`scale(${zoom})`}}>{world.topicData.map((t,i)=>{const [x,y]=positions[i%positions.length];const hot=active===t.name;const connected=active===null||active===t.name||(LINKS[active]||[]).includes(t.name)||(LINKS[t.name]||[]).includes(active);return <button key={t.name} className={`topic-orb ${world.tone} ${t.owner?'owned':''} ${hot?'selected':''} ${!connected?'faded':''}`} style={{left:x+'%',top:y+'%',width:t.price>=50?112:t.price>=25?100:88,height:t.price>=50?112:t.price>=25?100:88}} onMouseEnter={()=>setActive(t.name)} onMouseLeave={()=>setActive(null)} onClick={()=>setActive(t.name)}><span className="orb-shine"/><strong>{t.name}</strong><small>{t.owner||'£'+t.price}</small>{t.owner&&<span className="owner-mark">♛</span>}</button>})}<svg className="topic-lines" viewBox="0 0 1000 620" preserveAspectRatio="none">{world.topicData.map((t,i)=>{const [x,y]=positions[i%positions.length];const target=(LINKS[t.name]||[]).find(n=>world.topicData.some(o=>o.name===n));if(!target)return null;const j=world.topicData.findIndex(o=>o.name===target);const [x2,y2]=positions[j%positions.length];return <line key={t.name+target} x1={x*10} y1={y*6.2} x2={x2*10} y2={y2*6.2} className={active&&(active===t.name||active===target)?'hot':''}/>})}</svg><div className={`topic-core ${world.tone}`}><strong>{world.name}</strong><small>CONNECTED WORLD</small></div></div></>}
          <div className="frame-label"><span className="kicker">LEVEL {world?'02':'01'}</span><b>{world?'THE TERRITORIES':'THE WORLDS'}</b></div><div className="frame-tip">{world?'Hover or select a territory':'Click a world to enter'}</div>{!world&&<div className="frame-help">Explore worlds <span>·</span> Search anything</div>}
        </div>
      </section>
      <section className="feature-strip"><div><b>01 / DISCOVER</b><span>Find a territory worth owning.</span></div><div><b>02 / CONQUER</b><span>Claim it before somebody else does.</span></div><div><b>03 / DEFEND</b><span>Return when your empire is attacked.</span></div><div><b>04 / SHARE</b><span>Every conquest becomes public.</span></div></section>
      <section id="activity" className="below-grid"><div className="panel"><span className="kicker">02 / ACTIVITY</span><h3>Live conquests.</h3>{[['@northstar','conquered','AI','£32'],['@orbital','defended','Space','£47'],['@foundry','conquered','Ireland','£27'],['@pixelworks','conquered','Gaming','£41']].map(r=><div className="activity-row" key={r.join('-')}><Crown size={14}/><span><b>{r[0]}</b> {r[1]} <strong>{r[2]}</strong></span><strong>{r[3]}</strong></div>)}</div><div className="panel" id="rankings"><span className="kicker">03 / RANKINGS</span><h3>Top empires.</h3>{[['@northstar','£1,482'],['@orbital','£921'],['@foundry','£744'],['@pixelworks','£511']].map((r,i)=><div className="rank-row" key={r[0]}><small>0{i+1}</small><b>{r[0]}</b><strong>{r[1]}</strong></div>)}</div></section>
      <section id="how" className="how"><span className="kicker">04 / HOW IT WORKS</span><h2>A marketplace disguised<br/>as a game.</h2></section>
    </main>
    {activeTopic&&<aside className="detail-drawer"><button className="drawer-close" onClick={()=>setActive(null)}><X size={16}/></button><span className="drawer-kicker"><span className={`search-dot ${world?.tone||'mint'}`}/> TERRITORY</span><h3>{activeTopic.name}</h3><p>{activeTopic.owner?<><Crown size={14}/> Owned by <b>{activeTopic.owner}</b></>:'Unclaimed territory'}</p><div className="drawer-stats"><div><small>CURRENT STAKE</small><b>£{(activeTopic.owner?activeTopic.stake:0).toLocaleString()}</b></div><div><small>{activeTopic.owner?'NEXT PRICE':'STARTING PRICE'}</small><b>£{nextPrice(activeTopic).toLocaleString()}</b></div></div><button className="claim-btn" onClick={()=>claim(activeTopic)}>{activeTopic.owner?<><Shield size={15}/> Conquer for £{nextPrice(activeTopic)}</>:<><Sparkles size={15}/> Claim for £{nextPrice(activeTopic)}</>}</button><small className="demo-note">Demo mode — payments come next.</small></aside>}
    <footer><span className="brand small">EMPIRE<span>.LOL</span></span><span>Own the internet. One territory at a time.</span><span>© 2026 Empire</span></footer>
  </div>
}

createRoot(document.getElementById('root')).render(<App/>);
